version: "0.1.0"

app:
  debug: false
  first_run: true
  language: "zh_CN"
  theme: "light"

screen:
  monitor_mode: "fullscreen"  # fullscreen, custom, grid
  custom_region:
    x: 0
    y: 0
    width: 1920
    height: 1080
  grid_layout:
    rows: 2
    columns: 2
    spacing: 10

ocr:
  engine: "tesseract"  # tesseract, paddleocr
  language: "ch"
  confidence_threshold: 0.6
  use_gpu: false
  num_threads: 4
  batch_size: 1
  paddle:
    model_dir: ""
    use_det: true
    use_cls: true
    use_server_mode: false
  tesseract:
    executable_path: ""
    tessdata_dir: ""
    config: ""
  roi:
    system_name:
      enabled: true
      x: 0
      y: 0
      width: 200
      height: 30
    ship_table:
      enabled: true
      x: 0
      y: 0
      width: 400
      height: 200

notification:
  enabled: true
  methods:
    - type: "webhook"
      url: ""
      enabled: false
    - type: "email"
      smtp_server: ""
      smtp_port: 587
      username: ""
      password: ""
      enabled: false
  rules:
    - condition: "ship_detected"
      priority: "high"
      methods: ["webhook", "email"]
    - condition: "system_changed"
      priority: "medium"
      methods: ["webhook"]

appearance:
  theme: "light"  # light, dark
  font_size: 12
  window_size:
    width: 800
    height: 600
  window_position:
    x: 100
    y: 100 